### ISSUE TITLE
correct load

### ISSUE THREAD

**Issue by rimusz** [AntonioMeireles/coreos-xhyve#5]
using `corectl load someprofile.toml` with more than one VM e.g.:

```
[containerLand]
...
[containerLand2]
...
[containerLand3]
...
```

VMs should be booted as per listed order in *.toml file

**Comment by AntonioMeireles** [comment]
yes, makes sense. digging.

**Comment by rimusz** [comment]
cool, thanks
it is very useful having just one profile file to boot more than one VM

**Comment by rimusz** [comment]
shall we support different file extensions per type:

```
*.toml 
*.yaml
*.json
```

**Comment by AntonioMeireles** [comment]
some notes: 
- fwiw, we support on `load` config files i any of `toml`, `yaml` or `json` _just_ because we get that for _free_ due to our use of [cobra](https://github.com/spf13/cobra) and [viper](https://github.com/spf13/viper) on the cli. If we should advertise that or just stick to one of those is a good question to which feedback is welcome.
- [viper](https://github.com/spf13/viper) after loading the config files stores their content as a `golang` `map` which by [definition](https://blog.golang.org/go-maps-in-action) is not iterable in a deterministic fashion. Since #7 we get around that by ordering the VMs by alphabetical order before loading them.
  
  Albeit this ensures that VMs will always be started by the same order i'm aware that this is a weaker form of what was requested by @rimusz here, ence i'm leaving this open for now.
  
  End goal is not to complicate too much configuration in `corectl` since in general terms one should probably ensure service/feature availability (provided by a given VM) either at cloud-config (systemd) level or even k8s level.

**Comment by rimusz** [comment]
we can close this one too
