### ISSUE TITLE
Warn messages on corectl commands

### ISSUE THREAD

**Issue by kikulikov** [AntonioMeireles/coreos-xhyve#94]
All `corectl` and `corectld` commands shows warnings like below

```
^^>>> corectl ls
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)
locally available images
```

**Comment by AntonioMeireles** [comment]
Hi @cyrillk 

thanks for reporting! that warning is (well, should be, in the general case) innocuous. It's just telling us that macOS hasn't yet set in the host's filesystem a default "Internet Connection Sharing" config, and so, instead of reading/consuming it we're attempting to use reasonable defaults. 
assuming that everything is working this is just background noise. Other than this, things are working for you, right ?

**Comment by kikulikov** [comment]
@AntonioMeireles Thank you for the reply. Yes, it seems to work fine.

**Comment by AntonioMeireles** [comment]
@cyrillk thanks and great to hear!
